### ISSUE TITLE
Resolve file handling on Windows 10

### ISSUE THREAD

**Issue by cortl** [acrosman/image2pattern#25]
**Describe the bug**

**To Reproduce**
1. `npm install && npm start`
2. Click on choose a file and select .\sample_images\AHC_4958.png'
3. Click generate Image

[4900:1022/182225.581:ERROR:CONSOLE(5509)] "SyntaxError: Unexpected token / in J                                              SON at position 0", source: chrome-devtools://devtools/bundled/shell.js (5509)
{ imgMaxWidth: 150,
  imgMaxHeight: 150,
  outputLocation: './outputs',
  colorMode: 'fullcolor',
  colorCount: '64',
  darkColor: 1145324799,
  lightColor: 4294910719,
  edgeMargin: '50',
  pageMargin: '50',
  boxSize: '10',
  lineColor: '#000000',
  breakColor: '10000',
  fillOpacity: '0.3' }
(node:4900) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir 'C:\Users\Cortlan Bainbridge\projects\image2pattern\outputs\images'
    at fs.mkdirSync (fs.js:872:3)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:727:16)
    at sync (C:\Users\Cortlan Bainbridge\projects\image2pattern\node_modules\mkdirp\index.js:71:13)
    at sync (C:\Users\Cortlan Bainbridge\projects\image2pattern\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\Cortlan Bainbridge\projects\image2pattern\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Cortlan Bainbridge\projects\image2pattern\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Cortlan Bainbridge\projects\image2pattern\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Cortlan Bainbridge\projects\image2pattern\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Cortlan Bainbridge\projects\image2pattern\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Cortlan Bainbridge\projects\image2pattern\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Cortlan Bainbridge\projects\image2pattern\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Cortlan Bainbridge\projects\image2pattern\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Cortlan Bainbridge\projects\image2pattern\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Cortlan Bainbridge\projects\image2pattern\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Cortlan Bainbridge\projects\image2pattern\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Cortlan Bainbridge\projects\image2pattern\node_modules\mkdirp\index.js:78:17)
(node:4900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Expected behavior**
Image is generated without error

**Screenshots**

**Image used**
sample_images\AHC_4958.png

**Desktop (please complete the following information):**
- OS: Windows 10

*Additional Information*
Same thing happens when I click Generate Pattern button as well.

**Comment by acrosman** [comment]
Thanks for posting this. Looks like Windows is handling existing directories/files differently from Mac and Linux.

Can you run `npm run gen-test` and see what happens?
